package Vista;

/**
 *
 * @author daniel
 */
public class Home extends javax.swing.JFrame {
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuSolicitud = new javax.swing.JMenu();
        subSolicitar = new javax.swing.JMenuItem();
        menuVisualizar = new javax.swing.JMenu();
        subEntradas = new javax.swing.JMenuItem();
        subSalidas = new javax.swing.JMenuItem();
        munuRestringir = new javax.swing.JMenu();
        subRestringir = new javax.swing.JMenuItem();
        menuGenerar = new javax.swing.JMenu();
        subCsv = new javax.swing.JMenuItem();
        menuAlertas = new javax.swing.JMenu();
        subAlerta = new javax.swing.JMenuItem();
        menuGestionar = new javax.swing.JMenu();
        subStock = new javax.swing.JMenuItem();
        subUsuario = new javax.swing.JMenuItem();
        subProducto = new javax.swing.JMenuItem();
        subPendiente = new javax.swing.JMenuItem();
        menuEntrada = new javax.swing.JMenu();
        subEntradaProducto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N

        menuSolicitud.setText("Solicitar");

        subSolicitar.setText("Productos");
        menuSolicitud.add(subSolicitar);

        barraMenu.add(menuSolicitud);

        menuVisualizar.setText("Visualizar");

        subEntradas.setText("Entradas");
        menuVisualizar.add(subEntradas);

        subSalidas.setText("Salidas");
        menuVisualizar.add(subSalidas);

        barraMenu.add(menuVisualizar);

        munuRestringir.setText("Restringir Productos");

        subRestringir.setText("A departamentos");
        munuRestringir.add(subRestringir);

        barraMenu.add(munuRestringir);

        menuGenerar.setText("Generar Archivos");

        subCsv.setText(".CSV");
        menuGenerar.add(subCsv);

        barraMenu.add(menuGenerar);

        menuAlertas.setText("Alerta");

        subAlerta.setText("Mostar alertas");
        menuAlertas.add(subAlerta);

        barraMenu.add(menuAlertas);

        menuGestionar.setText("Gestionar");

        subStock.setText("Stock");
        menuGestionar.add(subStock);

        subUsuario.setText("Usuarios");
        menuGestionar.add(subUsuario);

        subProducto.setText("Productos");
        menuGestionar.add(subProducto);

        subPendiente.setText("Pedido pendiente");
        menuGestionar.add(subPendiente);

        barraMenu.add(menuGestionar);

        menuEntrada.setText("Entrada");

        subEntradaProducto.setText("De producto");
        menuEntrada.add(subEntradaProducto);

        barraMenu.add(menuEntrada);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JMenu menuAlertas;
    public javax.swing.JMenu menuEntrada;
    public javax.swing.JMenu menuGenerar;
    public javax.swing.JMenu menuGestionar;
    public javax.swing.JMenu menuSolicitud;
    public javax.swing.JMenu menuVisualizar;
    public javax.swing.JMenu munuRestringir;
    public javax.swing.JMenuItem subAlerta;
    public javax.swing.JMenuItem subCsv;
    public javax.swing.JMenuItem subEntradaProducto;
    public javax.swing.JMenuItem subEntradas;
    public javax.swing.JMenuItem subPendiente;
    public javax.swing.JMenuItem subProducto;
    public javax.swing.JMenuItem subRestringir;
    public javax.swing.JMenuItem subSalidas;
    public javax.swing.JMenuItem subSolicitar;
    public javax.swing.JMenuItem subStock;
    public javax.swing.JMenuItem subUsuario;
    // End of variables declaration//GEN-END:variables
}
